# Single source of truth for the project version.
# Bump these when releasing.
set(PIXELFORGE_VERSION_MAJOR 0)
set(PIXELFORGE_VERSION_MINOR 1)
set(PIXELFORGE_VERSION_PATCH 0)
set(PIXELFORGE_VERSION
    "${PIXELFORGE_VERSION_MAJOR}.${PIXELFORGE_VERSION_MINOR}.${PIXELFORGE_VERSION_PATCH}")
